name: twitter_clone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  like_button: ^2.0.5
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  modal_progress_hud_nsn: ^0.3.0






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - images/

#  fonts:
#    - family: Spartan MB
#      fonts:
#        - asset: fonts/SpartanMB-Black.otf
#          weight: 900
